// DO NOT EDIT MANUALLY. Generated by flutter_gherkin_parser.
import 'package:flutter_gherkin_parser/integration_test_helper.dart';
import 'test_config.dart';

import 'generated/settings.dart' as settings;
import 'generated/home.dart' as home;
import 'generated/login.dart' as login;

void main() {
  IntegrationTestHelper(config: config);

  settings.main();
  home.main();
  login.main();
}
