// DO NOT EDIT MANUALLY. Generated by flutter_bdd_suite.
import 'package:flutter_bdd_suite/integration_test_helper.dart';
import 'test_config.dart';

import 'generated/auth/login.dart' as login;
import 'generated/dashboard/employee_directory.dart' as employee_directory;

void main() async {
  final helper = await IntegrationTestHelper.create(config: config);

  // Register suite-level setUpAll/tearDownAll exactly once for all features.
  // Individual feature runners do not call registerSuiteHooks themselves.
  helper.registerSuiteHooks();

  login.run(helper);
  employee_directory.run(helper);
}
