// DO NOT EDIT MANUALLY. Generated by flutter_bdd_suite.
import 'package:flutter_bdd_suite/integration_test_helper.dart';
import 'test_config.dart';

import 'generated/auth/login.dart' as login;

void main() {
  IntegrationTestHelper(config: config);

  login.main();
}
