include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

formatter:
  page_width: 80

linter:
  rules:
    depend_on_referenced_packages: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
