import 'dart:convert' show jsonEncode;

import 'package:flutter_bdd_suite/src/models/step_model.dart';

/// Parsed representation of a Gherkin `Scenario` or `Scenario Outline` row as
/// produced by the Gherkin parser.
///
/// This is the internal model used while building the parse tree; the
/// test-runner uses [ScenarioInfo] (a lighter data-transfer object) instead.
class Scenario {
  /// The scenario title as written after the `Scenario:` keyword.
  final String name;

  /// Line number of the `Scenario:` keyword in the feature file (1-based).
  final int line;

  /// Gherkin tags applied to this scenario (e.g. `['@smoke', '@regression']`).
  final List<String> tags;

  /// Steps belonging to this scenario in declaration order.
  final List<Step> steps = [];

  Scenario({required this.name, required this.line, this.tags = const []});

  Map<String, dynamic> toJson() {
    return {
      'name': name,
      'line': line,
      'tags': tags,
      'steps': steps.map((step) => step.toJson()).toList(),
    };
  }

  @override
  String toString() {
    return jsonEncode(toJson());
  }
}

/// Lightweight data-transfer object that carries the information the test
/// runner needs to execute a single scenario.
///
/// Generated by the code-generator and passed to
/// [IntegrationTestHelper.testScenario] and throughout the lifecycle callbacks.
class ScenarioInfo {
  /// The scenario title as written after the `Scenario:` keyword.
  final String scenarioName;

  /// Line number of the `Scenario:` keyword in the feature file (1-based).
  final int line;

  /// Gherkin tags applied to this scenario (e.g. `['@smoke', '@regression']`).
  ///
  /// Includes tags inherited from the parent `Feature:` block when the
  /// generator flattens them.
  final List<String> tags;

  /// JSON-encoded step list produced by the code-generator.
  ///
  /// Each entry is a JSON object with at minimum a `"text"` key (the resolved
  /// step text) and a `"line"` key (the step's line number in the feature
  /// file).
  final List<String> steps;

  ScenarioInfo({
    required this.scenarioName,
    required this.line,
    this.tags = const [],
    this.steps = const [],
  });
}

/// The execution outcome of a scenario after all its steps have run.
enum ScenarioExecutionStatus {
  /// Every step in the scenario completed without error.
  passed,

  /// At least one step threw an error or assertion failure.
  failed,

  /// The scenario was skipped, typically because a prior background step failed.
  skipped,
}

/// Rich context object passed to [LifecycleListener.onAfterScenario].
///
/// Provides both the original [ScenarioInfo] and the final [status] so that
/// hooks and reporters can react to the outcome without having to track per-step
/// state themselves.
class ScenarioResult {
  /// The scenario that just finished executing.
  final ScenarioInfo scenario;

  /// The overall outcome of the scenario.
  final ScenarioExecutionStatus status;

  const ScenarioResult({required this.scenario, required this.status});

  /// Convenience accessor – mirrors [ScenarioInfo.scenarioName].
  String get scenarioName => scenario.scenarioName;
}
